Repository DDIT-JINRO/jinro_back_public, pull requests merged in 2025-08, with the labels that each got.

#7 [feat] develop 머지
  src/main/resources/static/css/chatModal.css
  src/main/resources/static/css/comm/peer/teen/teenDetail.css
  src/main/resources/static/css/common/userCommon.css
  src/main/resources/static/css/main.css
  src/main/resources/static/js/cdp/rsm/rsmb/resumeBoardDetail.js
  src/main/resources/static/js/comm/path/pathDetail.js
  src/main/resources/static/js/comm/peer/teen/teenDetail.js
  src/main/resources/static/js/comm/peer/youth/youthDetail.js
  src/main/resources/static/js/content/main.js
  src/main/resources/static/js/include/chatModal.js
  src/main/webapp/WEB-INF/views/cdp/rsm/rsmb/resumeBoardDetail.jsp
  src/main/webapp/WEB-INF/views/comm/path/pathDetail.jsp
  src/main/webapp/WEB-INF/views/comm/peer/teen/teenDetail.jsp
  src/main/webapp/WEB-INF/views/comm/peer/youth/youthDetail.jsp
  src/main/webapp/WEB-INF/views/include/chatModal.jsp
Labels: enhancement

#13 [fix] JSP 에서 js 로드 이슈 수정
  src/main/resources/static/js/csc/inq/inqList.js
  src/main/resources/static/js/ertds/univ/uvivfb/selectInterviewList.js
  src/main/webapp/WEB-INF/views/comm/peer/alert.jsp
  src/main/webapp/WEB-INF/views/empt/ivfb/insertInterViewFeedbackView.jsp
Labels: bug

#15 [Feat] 메인 배너 CSS 수정, 직업, 학과 비교 플로팅 버튼 CSS 수정
  src/main/resources/static/css/common/userCommon.css
  src/main/resources/static/css/ertds/univ/dpsrch/deptList.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/pse/cr/crl/selectCareerList.css
  src/main/resources/static/js/content/main.js
  src/main/resources/static/js/ertds/univ/dpsrch/deptList.js
  src/main/resources/static/js/pse/cr/crl/selectCareerList.js
  src/main/webapp/WEB-INF/views/content/main.jsp
Labels: enhancement

#17 [fix] 08/29 수정사항 반영
  src/main/java/kr/or/ddit/admin/las/service/UsageStatsVO.java
  src/main/java/kr/or/ddit/test/service/TestService.java
  src/main/java/kr/or/ddit/test/service/TestVO.java
  src/main/java/kr/or/ddit/test/service/impl/TestMapper.java
  src/main/java/kr/or/ddit/test/service/impl/TestServiceImpl.java
  src/main/java/kr/or/ddit/test/web/TestController.java
  src/main/resources/mybatis/mapper/counselManagement-Mapper.xml
  src/main/resources/mybatis/mapper/paymentStats-Mapper.xml
  src/main/resources/mybatis/mapper/test-Mapper.xml
  src/main/resources/mybatis/mapper/umg-Mapper.xml
  src/main/resources/mybatis/mapper/usageStats-Mapper.xml
  src/main/resources/static/css/admin/umg/counselorManagement.css
  src/main/resources/static/css/cdp/rsm/rsm/resumeWriter.css
  src/main/resources/static/css/common/userCommon.css
  src/main/resources/static/css/ertds/univ/dpsrch/deptList.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/pse/cr/crl/selectCareerList.css
  src/main/resources/static/js/account/findId.js
  src/main/resources/static/js/account/login.js
  src/main/resources/static/js/account/loginReq.js
  src/main/resources/static/js/cdp/rsm/rsm/resumeWriter.js
  src/main/resources/static/js/comm/path/pathDetail.js
  src/main/resources/static/js/comm/peer/teen/teenDetail.js
  src/main/resources/static/js/comm/peer/youth/youthDetail.js
  src/main/resources/static/js/content/main.js
  src/main/resources/static/js/csc/inq/inqList.js
  src/main/resources/static/js/csc/not/adminNoticeList.js
  src/main/resources/static/js/empt/enp/enterprisePosting.js
  src/main/resources/static/js/empt/ivfb/insertInterViewFeedbackView.js
  src/main/resources/static/js/ertds/hgschl/HighSchoolList.js
  src/main/resources/static/js/ertds/univ/dpsrch/deptList.js
  src/main/resources/static/js/ertds/univ/uvivfb/selectInterviewList.js
  src/main/resources/static/js/include/admin/cmg/univManagement.js
  src/main/resources/static/js/include/admin/umg/counselorManagement.js
  src/main/resources/static/js/include/admin/umg/memberManagement.js
  src/main/resources/static/js/include/alarmModal.js
  src/main/resources/static/js/include/chatModal.js
  src/main/resources/static/js/include/cns/scm/scheduleManagement.js
  src/main/resources/static/js/include/cns/sidebar.js
  src/main/resources/static/js/include/cns/vac/vacation.js
  src/main/resources/static/js/mpg/mat/bmk/selectBookMarkList.js
  src/main/resources/static/js/prg/std/createStdGroup.js
  src/main/resources/static/js/prg/std/stdGroupDetail.js
  src/main/resources/static/js/pse/cr/cco/careerComparsionView.js
  src/main/resources/static/js/pse/cr/crl/selectCareerList.js
  src/main/webapp/WEB-INF/views/account/test.jsp
  src/main/webapp/WEB-INF/views/admin/umg/memberManagement.jsp
  src/main/webapp/WEB-INF/views/comm/peer/alert.jsp
  src/main/webapp/WEB-INF/views/content/main.jsp
  src/main/webapp/WEB-INF/views/empt/ivfb/insertInterViewFeedbackView.jsp
Labels: bug, enhancement

#22 master.yml
  .github/workflows/main.yml
Labels: enhancement

#21 [Feat] 메인 수정 및 관리자 고객센터 페이징처리 문제 수정
  src/main/java/kr/or/ddit/account/lgn/web/LoginController.java
  src/main/java/kr/or/ddit/account/lgn/web/LoginRestController.java
  src/main/java/kr/or/ddit/chat/service/impl/ChatRoomSessionManager.java
  src/main/java/kr/or/ddit/main/service/MemberVO.java
  src/main/java/kr/or/ddit/pse/cat/service/impl/CareerAptitudeTestServiceImpl.java
  src/main/java/kr/or/ddit/util/pdf/service/impl/HTMLtoPdfServiceImpl.java
  src/main/resources/static/css/admin/admDashboard.css
  src/main/resources/static/css/admin/cmg/univManagement.css
  src/main/resources/static/css/cdp/rsm/rsm/resumeWriter.css
  src/main/resources/static/css/common/userCommon.css
  src/main/resources/static/css/main.css
  src/main/resources/static/images/main/mascot/mascot-mypage1.png
  src/main/resources/static/images/main/mascot/mascot-mypage2.png
  src/main/resources/static/js/account/login.js
  src/main/resources/static/js/cdp/rsm/rsm/resumeWriter.js
  src/main/resources/static/js/csc/inq/adminInqList.js
  src/main/resources/static/js/csc/not/adminNoticeList.js
  src/main/resources/static/js/include/admin/dashboard.js
  src/main/resources/static/js/include/alarmModal.js
  src/main/resources/static/js/include/header.js
  src/main/webapp/WEB-INF/views/account/login.jsp
  src/main/webapp/WEB-INF/views/admin/csc/inquiryManagement.jsp
  src/main/webapp/WEB-INF/views/admin/csc/noticeManagement.jsp
  src/main/webapp/WEB-INF/views/admin/dashboard.jsp
  src/main/webapp/WEB-INF/views/cdp/rsm/rsm/resumeWriter.jsp
  src/main/webapp/WEB-INF/views/content/main.jsp
  src/main/webapp/WEB-INF/views/include/footer.jsp
  src/main/webapp/WEB-INF/views/include/header.jsp
  src/main/webapp/WEB-INF/views/mpg/mat/bmk/selectBookmarkList.jsp
  src/main/webapp/WEB-INF/views/mpg/mat/csh/selectCounselingHistoryList.jsp
  src/main/webapp/WEB-INF/views/mpg/mat/reh/selectResumeHistoryList.jsp
  src/main/webapp/WEB-INF/views/mpg/mat/sih/selectSelfIntroHistoryList.jsp
  src/main/webapp/WEB-INF/views/mpg/mif/inq/selectMyInquiryView.jsp
  src/main/webapp/WEB-INF/views/mpg/mif/pswdchg/selectPasswordChangeView.jsp
  src/main/webapp/WEB-INF/views/mpg/mif/whdwl/selectWithdrawalView.jsp
  src/main/webapp/WEB-INF/views/mpg/pay/selectPaymentView.jsp
Labels: bug, enhancement

#24 [feat] 로드맵 결과를 추천직업 테이블에 저장
  .github/workflows/main.yml
  src/main/java/kr/or/ddit/pse/cat/service/impl/CareerAptitudeTestServiceImpl.java
  src/main/java/kr/or/ddit/rdm/service/RoadmapService.java
  src/main/java/kr/or/ddit/rdm/service/impl/RoadmapServiceImpl.java
  src/main/webapp/WEB-INF/views/include/header.jsp
Labels: bug, enhancement

#27 [Feat] 소셜로그인 유저 비밀번호 변경 페이지 이동 막기
  src/main/java/kr/or/ddit/mpg/mif/whdwl/service/impl/WithdrawalServiceImpl.java
  src/main/resources/mybatis/mapper/myInquiry-Mapper.xml
  src/main/resources/mybatis/mapper/withdrawal-Mapper.xml
  src/main/resources/static/js/mpg/mif/inq/selectMyInquiryView.js
  src/main/resources/static/js/mpg/mif/whdwl/selectWithdrawalView.js
  src/main/webapp/WEB-INF/views/mpg/mif/inq/selectMyInquiryView.jsp
  src/main/webapp/WEB-INF/views/mpg/mif/whdwl/selectWithdrawalView.jsp
Labels: enhancement

#29 [fix] 관리자, 상담사, 센터장 페이지 custom alert 수정
  src/main/resources/static/css/cns/cnsSideBar.css
  src/main/resources/static/css/cnsLeader/cnsLeaderSideBar.css
  src/main/resources/static/js/content/main.js
  src/main/resources/static/js/include/admin/cmg/activityManagement.js
  src/main/resources/static/js/include/admin/cmg/contestManagement.js
  src/main/resources/static/js/include/admin/cmg/enterpriseManagement.js
  src/main/resources/static/js/include/admin/cmg/reviewManagement.js
  src/main/resources/static/js/include/admin/cmg/univManagement.js
  src/main/resources/static/js/include/admin/umg/counselorManagement.js
  src/main/resources/static/js/include/admin/umg/memberManagement.js
  src/main/resources/static/js/include/admin/umg/sanctionsDescription.js
  src/main/resources/static/js/include/cns/counselChat.js
  src/main/resources/static/js/include/cns/csl/counselingLog.js
  src/main/resources/static/js/include/cns/sidebar.js
  src/main/resources/static/js/include/cns/vac/vacation.js
  src/main/resources/static/js/include/cnsLeader/csm/counselingLogManagement.js
  src/main/resources/static/js/include/cnsLeader/csm/counselorVacationManagement.js
  src/main/resources/static/js/include/cnsLeader/scm/scheduleManagement.js
  src/main/resources/static/js/include/cnsLeader/sidebar.js
  src/main/webapp/WEB-INF/views/include/cns/sidebar.jsp
  src/main/webapp/WEB-INF/views/include/cnsLeader/sidebar.jsp
Labels: bug
